"use strict";
const LINKS = [
    { id: 1, title: 'Latest News', desc: '最新情報を確認できますよ', url: '/page/news.html', category: 'extra' },
    { id: 2, title: 'Game List', desc: '公開中のゲーム一覧', url: '/page/gamelist.html', category: 'tools' },
    { id: 3, title: 'Tool List', desc: '公開中のツール一覧', url: '/page/toollist.html', category: 'tools' },
    { id: 4, title: 'Article List', desc: '公開中の記事一覧', url: '/page/articlelist.html', category: 'tools' },
    { id: 5, title: 'Notepad app', desc: '高機能なメモ帳', url: '/tools/notepad.html', category: 'tools' },
    { id: 6, title: 'Source code viewer', desc: 'ソースコードを確認', url: '/tools/sauceview.html', category: 'tools' },
    { id: 7, title: 'Proxy', desc: 'プロキシ通信が可能', url: '/tools/proxy.html', category: 'tools' },
    { id: 8, title: 'Link collection', desc: 'ショートカット一覧 (外部)', url: 'https://o-ngr.3do1.jp/', category: 'tools' },
    { id: 9, title: 'Link collection 2', desc: 'ショートカット一覧', url: '/page/links.html', category: 'tools' },
    { id: 10, title: 'Feeder open chat', desc: 'オープンチャット', url: 'https://www2.x-feeder.info/ms05', category: 'tools' },
    { id: 11, title: 'frame　opener', desc: 'フレームオープナー', url: '/tools/opener.html', category: 'tools' },
    { id: 12, title: 'truck game', desc: 'トロッコゲーム', url: '/truck/index.html', category: 'extra' },
    { id: 13, title: 'camera', desc: 'カメラ', url: '/tools/camera.html', category: 'tools' },
    { id: 14, title: 'nodemaster', desc: 'ノードゲーム', url: '/play/nodemaster.html', category: 'design' },
    { id: 15, title: 'musicvisualizer', desc: 'ミュージックビジュアライザー', url: '/tools/musicvisualizer.html', category: 'design' },
    { id: 16, title: 'percentencodingconverter', desc: 'パーセントエンドコンバータ', url: '/tools/percentencodingconverter.html', category: 'tools' },
    { id: 17, title: 'shader', desc: 'シェーダー', url: '/tools/shader.html', category: 'design' },
    { id: 18, title: 'Raymarched Band', desc: 'レイマーチ・バンド', url: '/tools/Raymarched Band.html', category: 'design' },
    { id: 19, title: 'mediaplayer', desc: 'メディアプレーヤ', url: '/tools/mediaplayer.html', category: 'tools' },
];
